name: PR Checks

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.md'

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1

      - run: npx oxlint@latest . --format github
